### ISSUE TITLE
Sequential Data?

### ISSUE THREAD

**Issue by adityamiskin** [safipatel/lnn-cancer-classification#1]
Hi, I'm new to this concept of Liquid Neural Network. As far as I have read about LNN's, they only work on sequential data. How are you using it for image classification as the data is not sequential?

**Comment by safipatel** [comment]
While you are correct that LNNs only work on sequential data, the models here actually take one dimension of an image as the sequence itself, while the other dimension is the input per sequence.
This happens after the CNN head, so we use each of the rows of results after the last CNN layer as one sequence of input to the LNN. And as you can see, the size of each row equals the input size of the liquid neural network.

I'll point you to [Yin et al.'s paper on CNN and RNN mixed model for image classification
](https://www.matec-conferences.org/articles/matecconf/abs/2019/26/matecconf_jcmme2018_02001/matecconf_jcmme2018_02001.html) and [CNN-RNN: A Unified Framework for Multi-label Image Classification by Wang et al. ](https://openaccess.thecvf.com/content_cvpr_2016/papers/Wang_CNN-RNN_A_Unified_CVPR_2016_paper.pdf) for more information about why this works and makes sense.
